#!/usr/bin/env bash
#script to install and configure HAproxy loadbalancer on the server(lb-01)
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# lets make a backup of the default cofig file (just incase ^_^)
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bckp
sudo chown -R "$USER":"$USER" /etc/default/
sudo chown -R "$USER":"$USER" /etc/haproxy/
loadbl_config=\
"defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend iamitsfoss-frontend
    bind *:80
    default_backend iamitsfoss-backend

backend iamitsfoss-backend
    balance roundrobin
    server 196966-web-01 100.26.221.164:80 check
    server 196966-web-02 54.209.95.25:80 check
"
sudo echo -e "$loadbl_config" > /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

if [[ "$(pgrep -f haproxy)" ]]; then
    sudo service haproxy restart
else
    sudo service haproxy start
fi
